site_name: FastHTTP Client
site_description: Fast and simple HTTP client library with async support and beautiful logging
site_author: White NEFOR
site_url: https://fasthttp-client.readthedocs.io/

docs_dir: docs

repo_url: https://github.com/ndugram/fasthttp
repo_name: ndugram/fasthttp

copyright: Copyright &copy; 2026 White NEFOR

# Navigation
nav:
  - Home: index.md
  - Home (EN): en/index.md
  - Quick Start (EN): en/quick-start.md
  - CLI (EN): en/cli.md
  - Configuration (EN): en/configuration.md
  - Examples (EN): en/examples.md
  - Middleware (EN): en/middleware.md
  - Pydantic (EN): en/pydantic-validation.md
  - HTTP/2 (EN): en/http2-support.md
  - API Reference (EN): en/api-reference.md
  - Главная (RU): ru/index.md
  - Быстрый старт (RU): ru/quick-start.md
  - CLI (RU): ru/cli.md
  - Конфигурация (RU): ru/configuration.md
  - Примеры (RU): ru/examples.md
  - Мидлвар (RU): ru/middleware.md
  - Pydantic (RU): ru/pydantic-validation.md
  - HTTP/2 (RU): ru/http2-support.md
  - API (RU): ru/api-reference.md

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
